name: Run Playwright Tests

on:
  push:
    branches:
      - main  
  pull_request:  

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Debug list contents of storage/
        run: ls -lh storage

      - name: Run Playwright tests
        run: npx playwright test || true  
        continue-on-error: true           
        
      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/